const List<String> kKonular = [
  'İşlem Yeteneği ve Sayı Kümeleri',
  'Tek ve Çift Sayılar ve İşaret İncelemesi',
  'Ardışık Sayılar',
  'Faktöriyel',
  'Basamak Kavramı',
  'Bölme ve Bölünebilme',
  'Asal Sayılar ve Asal Çarpanlara Ayırma',
  'EBOB ve EKOK',
  'Rasyonel Sayılar',
  'Birinci Dereceden Denklemler',
  'Birinci Dereceden Eşitsizlikler',
  'Mutlak Değer',
  'Üslü Sayılar',
  'Köklü Sayılar',
  'Çarpanlara Ayırma',
  'Oran ve Orantı',
  'Sayı ve Kesir Problemleri',
  'Yaş Problemleri',
  'Yüzde, Kâr, Zarar ve Karışım Problemleri',
  'İşçi ve Havuz Problemleri',
  'Hareket Problemleri',
  'Tablo ve Grafik Problemleri',
  'Kümeler',
  'Fonksiyonlar',
  'İşlem ve Periyodik Tekrar Eden Durumlar',
  'Permütasyon',
  'Kombinasyon',
  'Olasılık',
  'Sayısal Mantık',
];
